import { StyleSheet, Platform } from 'react-native';
import { Dimensions } from 'react-native';

import { getStatusBarHeight } from 'react-native-status-bar-height';
const STATUS_BAR_HEIGHT = getStatusBarHeight();

const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

export default StyleSheet.create({
    container: {
        backgroundColor:'#ffffff',
        flex: 1,
        flexGrow: 1,
        flexDirection: "column",
        width:'100%',
        height:'100%',
        padding:10,
        position:'relative',
    },
    addStatusbarPadding:{
        paddingTop: STATUS_BAR_HEIGHT-20,
    },
    headerContainerContent: {
        flex:1,
        flexDirection: "row",
        justifyContent:'space-between',
        alignItems:'center',
        width:'100%',
        height:'100%',
    },
    headerContainer: {
        height:40,
        width:'100%',
        flexShrink: 0,
    },
    homeScrollView: {
        marginTop: 10,
        height: 'auto',
        flexGrow: 1,
    },
    logoButton: {
        width: 95,
        marginRight: 10,
        justifyContent:'center',
        alignItems:'center',
    },
    voucher: {
        position:'relative',
        width:45,
        height:40,
        marginLeft: 10,
    },
    vouchersInside: {
        position:'absolute',
        width:'100%',
        height:'100%',
        top:0,
        left:0,
        alignItems:'center',
        justifyContent:'center',
    },
    voucherText: {
        color:'#2E67B2',
        fontSize: 16,
        fontFamily: "NunitoSans-Bold",
    },
    searchCity: {
        flex: 1,
        backgroundColor:'#2E67B2',
        height:'100%',
        borderRadius:20,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        paddingRight: 14,
    },
    searchCityLeft: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'center',
        paddingLeft: 16,
        paddingRight: 2,
    },
    headerMyCity: {
        fontFamily: "NunitoSans-Regular",
        fontSize:16,
        color:'white',
        marginLeft:5,
        marginRight:5,
    },
    headerMyCityBig: {
        fontFamily: "NunitoSans-Bold",
        fontWeight:'bold',
        fontSize:16,
        color:'white',
        marginLeft:10,
        marginRight:10,
    },
    card: {
        width:'100%',
        minHeight:150,
        position:'relative',
        marginBottom:10,
        overflow:'hidden',
        borderRadius:15,
    },
    cardBackground: {
            width:'100%',
            height:'100%',
            flex:1,
            // resizeMode: 'cover',
            justifyContent:'center',
    },
    cardBackgroundBottom: {
        width:'100%',
        height:'100%',
        flex:1,
        resizeMode: 'cover',
        justifyContent:'flex-end',
    },
    voucherTextCardSmall: {
        fontFamily:'NunitoSans-Bold',
        fontWeight:'bold',
        fontSize:11,
        color:'white',
    },
    closeCard: {
        position:'absolute',
        right:15,
        top:15,
        zIndex:5,
    },
    overlay: {
        position:'absolute',
        width:'100%',
        height:'100%',
        flex:1,
        resizeMode: 'cover',
        justifyContent:'flex-end',
        left:0,
        right:0,
        opacity: 0.2,
        backgroundColor: 'black',
    },
    disabledVoucher: {
        position:'absolute',
        width:'100%',
        height:'100%',
        flex:1,
        left:0,
        right:0,
        zIndex: 10,
        opacity: 0.6,
        backgroundColor: '#cecece',
    },
    expiredContainer: {
        position:'absolute',
        width:'100%',
        height:'100%',
        top:0,
        left:0,
        alignItems:'center',
        justifyContent:'center',
    },
    expiredElement: {
        alignItems:'center',
        justifyContent:'center',
        borderWidth:2,
        borderStyle: 'dashed',
        borderColor:'white',
        borderRadius: 1,
        width:200,
        height:50,
        borderRadius:15,
    },
    expiredText: {
        fontFamily:'NunitoSans-Bold',
        fontWeight:'bold',
        fontSize:24,
        textTransform:'uppercase',
        color:'white',
        letterSpacing: 4,
    },
    voucherTextCard: {
        fontFamily:'NunitoSans-Bold',
        fontSize:22,
        color:'white',
        marginBottom:10,
        fontWeight:'bold',
    },
    voucherButton: {
        width:120,
        height:30,
        backgroundColor:'#2E67B2',
        fontFamily:'NunitoSans-Regular',
        fontSize:12,
        textAlign:'center',
        justifyContent:'center',
        alignItems:'center',
        borderRadius:10,
    },
    voucherButtonText: {
        fontFamily:'NunitoSans-Regular',
        fontSize:12,
        textAlign:'center',
        color:'white',
    },
    voucherPadding: {
        paddingLeft:25,
        width:230,
    },
    voucherContainer: {
        padding:10,
        width:'100%',
    },
    voucherTextCardBig: {
        fontFamily:'NunitoSans-Regular',
        color:'white',
        fontSize:21,
        fontWeight:'bold',
    },
    cardContainer: {
        flex:1,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        marginBottom:10,
    },
    smallCard: {
        width:'49%',
        height:119,
        position:'relative',
        marginBottom:10,
        overflow:'hidden',
        borderRadius:15,
    },
    smallCardText: {
        fontFamily:'NunitoSans-Bold',
        fontWeight:'bold',
        fontSize:16,
        color:'white',
    },
    seeVouchersButton: {
        width:'100%',
        height:40,
        borderColor: '#2E67B2',
        borderWidth: 2,
        borderRadius:50,
        marginBottom:10,
        justifyContent:'center',
        alignItems:'center',
    },
    seeVouchersText: {
        fontFamily:'NunitoSans-Regular',
        fontSize:16,
        color:'black',
    },
    navigateCity: {
        marginTop:10,
        marginBottom:20,
    },
    cityTags: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'flex-start',
    },
    tag: {
        marginRight:5,
        borderColor: '#2E67B2',
        borderWidth: 1,
        borderRadius:16,
        marginBottom:10,
        justifyContent:'center',
        alignItems:'center',
        flexDirection:'row',
        paddingLeft:10,
        paddingRight:10,
        paddingTop:5,
        paddingBottom:5,
        height:30,
    },
    myAccount: {
        height:40,
        backgroundColor:'#2E67B2',
        width:177,
        borderRadius:20,
        marginLeft:'auto',
        marginRight:'auto',
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
        marginBottom:10,
    },
    myAccountText: {
        fontFamily:'NunitoSans-Regular',
        fontSize:16,
        color:'white',
        marginLeft:10,
    },
    tagText: {
        fontFamily:'NunitoSans-Regular',
        fontSize:14,
        color:'#2E67B2',
    },
    tagApasat: {
        backgroundColor:'#2E67B2',
        borderColor:'#2E67B2',
    },
    categories: {
        width:'100%',
        height:40,
        marginTop: 10,
    },
    adaugaVaucher: {
        backgroundColor:'#2E67B2',
        justifyContent:'center',
        padding: 20,
        height: 200,
        flexShrink: 0,
    },
    adaugaVoucherText: {
        marginBottom:10,
        fontFamily:'NunitoSans-Bold',
        fontWeight:'bold',
        color:'white',
        fontSize:21,
    },
    adaugaVoucherInput: {
        backgroundColor: 'white',
        flex: 1,
        width: '100%',
        maxWidth: '100%',
        overflow: 'hidden',
        height: 35,
        borderRadius: 20,
        fontFamily: 'NunitoSans-Bold',
        fontWeight: 'bold',
        color: '#2E67B2',
        fontSize: 12,
        marginBottom: 0,
    },
    adaugaVoucherTextSmall: {
        fontFamily:'NunitoSans-Light',
        color:'white',
        fontSize:14,
        marginTop: 10,
    },
    saveNewActivationCode: {
        marginLeft: 10,
        height: 35,
        paddingHorizontal: 20,
        flexShrink: 0,
        backgroundColor: '#2E67B2',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 20,
    },
    saveNewActivationCodeText: {
        textAlign: 'center',
        fontFamily: 'NunitoSans-Light',
        fontSize: 14,
        color: 'white',
    },
    transparentHeaderContainer: {
        width:'100%',
        height:'100%',
        height:39,
        backgroundColor:'transparent',
        position:'absolute',
        top:20,
        paddingLeft:10,
        paddingRight:10,
        zIndex:10,

    },
    whiteHeaderContainer: {
        width:'100%',
        height:'100%',
        height:70,
        backgroundColor:'white',
        position:'absolute',
        zIndex:10,

    },
    headerTransparent: {
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        width:'100%',
        height:'100%',
    },
    headerWhite: {
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        width:'100%',
        height:'100%',
        padding:10,
    },
    searchCityTransparent: {
        width:'80%',
        backgroundColor:'white',
    },
    headerTransparentModified: {
        width:'100%',
        marginLeft:'auto',
        marginRight:'auto',
    },
    dashboardContainer: {
        position:'relative',
        height:'auto',
        width:'95%',
        marginLeft:'auto',
        marginRight:'auto',
        borderTopRightRadius:50,
        borderTopLeftRadius:50
    },
    boucherDetailImagine: {
        position:'absolute',
        width:108,
        height:108,
        borderRadius:50,
        overflow:'hidden',
    },
    shareText: {
        fontFamily:'NunitoSans-Regular',
        color:'#747474',
        fontSize:14,
        marginLeft:10,
    },
    shareContainer: {
        width:200,
        height:45,
        borderColor:'#2E67B2',
        borderWidth: 1,
        borderRadius:50,
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
        marginLeft:'auto',
        marginRight:'auto',
        marginBottom:40,
    },
    dashboardInside: {
        width: '100%',
        height: '100%',
        marginTop: 60,
        paddingBottom: 80,
    },
    detaliuVoucherTitle: {
        textAlign:'center',
        fontFamily:'NunitoSans-Bold',
        fontWeight:'bold',
        color:'#2E67B2',
        fontSize:18,
        marginBottom:20,
    },
    detaliuVoucherText: {
        fontFamily:'NunitoSans-Light',
        fontSize:16,
        color:'#535252',
        textAlign:'center',
        marginBottom:20,
        width:'100%',
        marginLeft:'auto',
        marginRight:'auto',
    },
    useVoucherButton: {
        alignItems:'center',
        justifyContent:'center',
        width:'100%',
        height:52,
        backgroundColor:'#EFEFEF',
        borderRadius:20,
        marginTop:20,
    },
    useVoucherText: {
        fontFamily:'NunitoSans-Regular',
        fontSize:16,
        color:'black',
    },
    butonTrimite: {
        alignItems:'center',
        justifyContent:'center',
        width:'100%',
        borderWidth:2,
        borderStyle: 'dashed',
        borderColor:'#2E67B2',
        borderRadius: 1,
        height:163,
        marginBottom:40,
        borderRadius:20,
    },
    succesImage: {
        marginLeft:'auto',
        marginRight:'auto',
        marginTop:20,
        marginBottom:20,
    },
    succesText: {
        width:'80%',
        marginLeft:'auto',
        marginRight:'auto',
    },
    expDateContainer: {
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
        width:'100%',
        marginBottom:20,
    },
    dataExpirare: {
        fontFamily:'NunitoSans-Light',
        fontSize:16,
        color:'#000000',
        marginLeft:10,
    },
    ListHeaderText: {
        fontFamily:'NunitoSans-Bold',
        fontWeight:'bold',
        fontSize:22,
        color:'black',
        marginTop:20,
    },
    listElement: {
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        borderTopColor: '#CECECE',
        borderTopWidth: 1,
        paddingTop:10,
        paddingBottom:10,
        paddingLeft:0,
        paddingRight:0,
        width:'100%',
    },
    listElementLeft: {
        width:'100%',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'flex-start'
    },
    discountTextContainer: {
        marginLeft:10,
    },
    discountTitle: {
        fontFamily:'NunitoSans-Regular',
        fontSize:14,
        color:'black',
    },
    discountAddress: {
        fontFamily:'NunitoSans-Regular',
        color:'#2E67B2',
        fontWeight:'bold',
        fontSize:12,
    },
    guidoAccountBtn: {
        backgroundColor:'#2E67B2',
        height:36,
        borderRadius:20,
        width:200,
        marginLeft:'auto',
        marginRight:'auto',
        alignItems:'center',
        justifyContent:'center',
        flexDirection:'row',
        padding:10,

    },
    guidoAccountBtnText: {
        fontFamily:'NunitoSans-Bold',
        fontWeight:'bold',
        color:'white',
        textTransform:'uppercase',
        fontSize:12,
    },
    otherBenefitsContainer: {
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        flexWrap:'wrap',
        marginBottom:40,
    },
    headerText: {
        fontFamily:'NunitoSans-Bold',
        fontWeight:'bold',
        color:'#2E67B2',
        fontSize:18,
        textAlign:'center',
    },
    informationsContainer: {
        marginBottom:10,
    },
    informationsElement: {
        flexDirection:'row',
        justifyContent:'flex-start',
        alignItems:'center',
        marginBottom:20,
        position:'relative',
        borderBottomWidth:1,
        borderColor:'#EFEFEF',
        paddingBottom:10,
    },
    informationsElementTextContainer: {
        marginLeft:10,
    },
    gpsButton: {
        borderRadius:15,
        backgroundColor:'#2E67B2',
        width:90,
        height:30,
        position:'absolute',
        flex:1,
        justifyContent:'center',
        textAlign:'center',
        right:0,
    },
    gpsText: {
        fontFamily:'NunitoSans-Regular',
        color:'white',
        fontSize:14,
        textTransform:'uppercase',
        textAlign:'center',
    },
    mapContainer: {
        width: '100%',
        height: 250,
        position: 'relative',
    },
    map: {
        width:'100%',
        height:'100%',
    },
    guidoAccountBtnAbsolute: {
        position: 'absolute',
        textAlign: 'center',
        left: 0,
        width: '100%',
        bottom: 10,
    },
    detailCard: {
        flex:1,
        borderWidth:1,
        borderColor:'#2E67B2',
        flexDirection:'row',
        justifyContent:'flex-start',
        borderRadius: 16,
        padding: 10,
        width: 230,
        height: 100,
        marginRight: 20,
    },
    detailCardContainer: {
        marginLeft:10,
        width:150,
    },
    detailCardTitle: {
        fontFamily:'NunitoSans-Regular',
        color:'black',
        fontSize:14,
        marginBottom:5,
        width:'100%',
    },
    detailCardText: {
        fontFamily:'NunitoSans-Regular',
        color:'#535252',
        fontSize:11,
        width:'100%',
    },
    containerFlex: {
        justifyContent:'center',
        alignItems:'center',
    },
    selectCategoriesText: {
        fontFamily:'NunitoSans-Light',
        fontSize:16,
        color:'#8D8D8D',
        textAlign:'center',
        marginTop:10,
        width:'80%'
    },
    selectCategoriesContainer: {
        flexGrow: 1,
        flexDirection:'row',
        flexWrap:'wrap',
        alignItems:'center',
        justifyContent:'flex-start',
    },
    continueButtonText: {
        fontFamily:'NunitoSans-Regular',
        fontSize:16,
        color:'white',
        textAlign:'center',
    },
    continueButton: {
        backgroundColor:'#2E67B2',
        width:'100%',
        height:52,
        justifyContent:'center',
        alignItems:'center',
        borderRadius:20,
        marginTop:20,
        marginBottom:40,
    },
    welcomeText: {
        marginTop:10,
        fontFamily:'NunitoSans-Bold',
        fontWeight:'bold',
        fontSize:36,
        color:'#2E67B2',
        textAlign:'center',
    },
    form: {
        width:'100%',
        marginTop:40,
        marginBottom:40,
    },
    userInput: {
        width:'100%',
        borderRadius:16,
        borderWidth:1,
        borderColor:'#2E67B2',
        fontFamily:'NunitoSans-Regular',
        fontSize:16,
        color:'black',
        paddingLeft:20,
        backgroundColor:'transparent',
        position:'relative',
        height: 45,
    },
    inputContainer: {
        width:'100%',
        position:'relative',
        marginTop:20,
    },
    termsContainer: {
        flexDirection:'row',
        justifyContent:'flex-start',
        alignItems:'center',
        width:'100%',
    },
    termsTextContaner: {
        flexDirection:'row',
        justifyContent:'flex-start',
        alignItems:'center',
        width: windowWidth<720 ? '90%' : '100%',
        flexWrap:'wrap'

    },
    termsText: {
        fontFamily:'NunitoSans-Regular',
        fontSize:12,
        color:'#1D78F3',
        borderColor:'#1D78F3',
        borderBottomWidth:1,
    },
    termeniText: {
        color:'#B9B9B9',
        fontFamily:'NunitoSans-Regular',
        fontSize:12,
        marginRight:10,
    },
    cityContainer: {
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        flexWrap:'wrap',
        marginBottom:40,
    },
    cityCard: {
        width:'48%',
        height:135,
        backgroundColor:'#dedede',
        marginBottom:15,
        borderRadius:20,
        justifyContent:'center',
        alignItems:'center',
        overflow:'hidden',
        padding: 10,
    },
    cityText: {
        fontFamily:'NunitoSans-Bold',
        fontWeight:'bold',
        fontSize:16,
        color:'#2E67B2',
        textAlign: 'center',
    },
    accountDetails: {
        marginTop:20,
        marginBottom:40,
    },
    avatarEditBtn: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        width: 26,
        height: 26,
        borderRadius: 100,
        borderWidth: 1,
        borderColor: '#ccc',
        backgroundColor: '#ffffff',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 100,
    },
    selectCategoriesProfile: {
        flexDirection:'row',
        justifyContent:'flex-start',
        flexWrap:'wrap',
        alignItems:'center',
    },
    pageTitleText: {
        fontFamily:'NunitoSans-Bold',
        fontWeight:'bold',
        fontSize:18,
        color:'#2E67B2',
    },
    
    // Swiper
    wrapper: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    slide: {
        width: '100%',
        backgroundColor: 'transparent',
        borderColor: '#cccccc',
        borderWidth: 1,
        borderRadius: 20,
        overflow: 'hidden',
    },
    swiperContainer: {
        width:'100%',
        height:300,
        paddingLeft:10,
        paddingRight:10,
        marginBottom:10,
    },
    
    // ISIC
    addCard: {
        backgroundColor:'#2E67B2',
        width:177,
        height:40,
        borderRadius:15,
        marginLeft:'auto',
        marginRight:'auto',
        marginTop: 10,
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
    },
    addCardText: {
        fontFamily:'NunitoSans-Regular',
        fontSize:16,
        marginLeft:10,
        color:'white',
    },
    imageCard: {
        position: 'relative',
        width:'100%',
        borderColor: '#cccccc',
        borderWidth: 1,
        borderRadius: 20,
        overflow: 'hidden',
    },
    cardDetail: {
        marginBottom:20,
        width:'100%',
    },
    buyActivationText: {
        fontFamily:'NunitoSans-Light',
        fontSize:12,
        color:'white',
        textAlign: 'center',
    },
    buyActivation: {
        width: 'auto',
        borderWidth: 2,
        borderColor: 'white',
        borderRadius: 20,
        height: 31,
        paddingHorizontal: 20,
        marginTop: 15,
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center',
    },
    expiredVoucherElement: {
        width:'100%',
        height:55,
        position:'relative',
        borderWidth: 1,
        borderRadius: 1,
        borderStyle: 'dashed',
        borderColor: 'white'
    },
    voucherElementOverlay: {
        justifyContent:'center',
        alignItems:'center',
        width:'100%',
        height:'100%',
        zIndex:10,
        position:'absolute',
        top:0,
        left:0,
    },
    expiredVoucherText: {
        color:'white',
        fontFamily:'NunitoSans-Bold',
        fontWeight:'bold',
        fontSize:16,
    },
    companyName: {
        fontFamily:'NunitoSans-Regular',
        color:'white',
        fontSize:18,
        fontWeight:'bold',
        position:'absolute',
        top:10,
        right:10,
        paddingLeft:20,
        textAlign: 'right',
    },
    companyNameModified: {
        fontFamily:'NunitoSans-Regular',
        color:'white',
        fontSize:18,
        fontWeight:'bold',
        // position:'absolute',
        // top:10,
        // right:10,
        // paddingLeft:20,
        // textAlign: 'right',
    },
    aboutGuido: {
        marginTop:30,
        marginLeft:'auto',
        marginRight:'auto',
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
        width:'100%',
    },
    aboutGuidoButton: {
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
        textAlign:'center',
        paddingVertical:8,
        paddingHorizontal:10,
        flex:1,
    },
    aboutGuidoButtonText: {
        flexShrink:1,
        color:'#000000',
        fontFamily:'NunitoSans-Regular',
        fontSize:14,
        textAlign:'center',
    },
    selectLanguage: {
        borderWidth:2,
        borderColor:'#2E67B2',
        borderRadius:20,
        paddingLeft:20,
        paddingRight:20,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        height:50,
        marginTop:20,
    },
    selectLanguageText: {
        color:'#2E67B2',
        fontFamily:'NunitoSans-Regular',
        fontSize:14,
        marginLeft:5,
        width:'100%',
        height:'100%',
        position:'absolute',
        top:0,
        left:0,
    },
    logoutText: {
        color:'#000000',
        fontFamily:'NunitoSans-Regular',
        fontSize:14,
        marginLeft:5,
        paddingTop: 13,
        paddingHorizontal: 10,
        paddingBottom: 12,
    },
    cardsTitle: {
        fontFamily:'NunitoSans-Bold',
        fontWeight:'bold',
        color:'black',
        textAlign:'center',
        fontSize:20,
    },
    cardStatus: {
        display: 'flex',
        flexDirection:'row',
        justifyContent: 'center',
        alignContent: 'center',
        alignItems: 'center',
        backgroundColor:'#4A4A4A',
        width:'100%',
        paddingHorizontal: 26,
        paddingVertical: 10,
    },
    cardStatusBubble: {
        width: 20,
        height: 20,
        borderRadius: 100,
        marginRight: 10
    },
    cardStatusText: {
        flexGrow: 1,
        fontFamily: 'NunitoSans-Bold',
        fontWeight: 'bold',
        color: 'white',
        fontSize: 18,
    },
    cardStatusTime: {
        fontFamily: 'NunitoSans-Regular',
        color: 'white',
        fontSize: 18,
    },
    cardFlip: {
        width:'100%',
        flex:1,
    },
    cardImageSide: {
        position: 'relative',
        flex:1,
        flexDirection:'column',
        width:'100%',
        height:'100%',
    },
    cardImageImg: {
        flex:1,
        flexGrow:1,
        width:'100%',
        height:'100%',
    },
    cardImageOverlay: {
        position:'absolute',
        top: 0,
        left: 0,
        width:'100%',
        height:'100%',
        zIndex: 10000,
    },
    cardSwitch: {
        position: 'absolute',
        top:'50%',
        right: 0,
        transform: [{translateY: -40}],
        width:40,
        height:80,
        backgroundColor:'rgba(0, 0, 0, 0.3)',
        borderTopLeftRadius: 12,
        borderBottomLeftRadius: 12,
        zIndex: 100,
        flexDirection:'column',
    },
    cardSwitchBtn: {
        flex: 1,
        alignItems:'center',
        justifyContent: 'center',
    },
    cardSwitchBullet: {
        width: 20,
        height: 20,
        borderRadius: 100,
        opacity: 0.8,
    },
    myCardBottomActions: {
        paddingLeft: 10,
        paddingVertical: 4,
        flexDirection:'row',
    },
    myCardBottomAction: {
        width:'50%',
        marginRight:10,
        borderWidth:2,
        borderColor:'#2E67B2',
        borderRadius:20,
        justifyContent:'center',
        alignItems:'center',
        flex: 1,
        flexDirection:'row',
        paddingVertical: 6,
        paddingHorizontal: 10,
    },
    myCardBottomActionText: {
        // flex: 1,
        fontFamily:'NunitoSans-Regular',
        color:'black',
        fontSize:14,
        marginLeft:10,
    },
    welcomeTop: {
        display: 'flex',
        width:'100%',
        height:250,
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:'white',
        paddingTop: 10,
    },
    welcomeContainer: {
        height:'100%',
        width:'100%',
        backgroundColor:'#EFEFEF',
        borderTopLeftRadius:60,
        borderTopRightRadius:60,
        flex:1,
        paddingTop:10,
    },
    inputFloatingLabelTextLabel: {
        fontFamily:'NunitoSans-Regular',
        color:'#7E7E7E',
        fontSize:16,
    }, 
    pickerIOS: {
        backgroundColor:'red',
    },
    termsText: {
        fontFamily:'NunitoSans-Regular',
        color:'#7E7E7E',
        fontSize:16,
        textAlign:'center'
    },
});